name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Create phony file for latex-action check
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: all
          FILE_DATA: # Empty
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          extra_system_packages: make
          compiler: make
          root_file: all
          args: -j
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
          name: phd_thesis.pdf
          path: phd_thesis.pdf
